services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FluidTYPO3\Vhs\ViewHelpers\:
    resource: '../Classes/ViewHelpers/*'
    public: true

  FluidTYPO3\Vhs\:
    resource: '../Classes/*'

  FluidTYPO3\Vhs\Utility\DispatcherProxy:
    autowire: true
    autoconfigure: true
    public: true

  TYPO3\CMS\Extbase\Mvc\Web\Routing\UriBuilder:
    autowire: true
    public: true
